### ISSUE TITLE
[Joss review] Kaplan Meier underflow

### ISSUE THREAD

**Issue by CamDavidsonPilon** [derrynknife/SurPyval#19]
For large datasets with lots of unique observation times, the `cumprod` in [KaplanMeierFitter](https://github.com/derrynknife/SurPyval/blob/master/surpyval/nonparametric/kaplan_meier.py#L9) will underflow due to the multiplication of many values less than 0. 

https://github.com/openjournals/joss-reviews/issues/3484

**Comment by derrynknife** [comment]
I'm not convinced this is such a large risk. As the number of unique observations grow, the at risk set 'r' will also be very large which in turn makes the d/r figure small making the eventual product series between a lot of numbers that are just below 1. I ran a simulation with 1 billion unique failures:

```python

def km(r, d):
    R = 1 - (d / r)
    R[np.isnan(R)] = 0
    return R

N = 1_000_000_000
r = np.array(range(1, N+1))[::-1]
d = np.ones(N)

np.seterr(under='raise')
km(r, d)
```

This did not result in an underflow.

I can add a check for underflow and change it to a sum of the log of the (1 - d/r) value which would add some numeric stability. But I'm not sure it will ever actually be invoked.

Thoughts?

**Comment by CamDavidsonPilon** [comment]
:+1: for testing. It's up to you if you want to add the check. I see no harm in using the log-transform, less some readability.

**Comment by derrynknife** [comment]
Yeah, I think I was just shying away from it for readability.

Will make the change.

Thanks

**Comment by derrynknife** [comment]
Created catch of floating point errors and use log in the event of such an error.

See:
653fbb1544dcd9b4dc7c40fcb707531f70ec4465
