### ISSUE TITLE
[Joss review] tests with real-life data, and compare to other implementations

### ISSUE THREAD

**Issue by CamDavidsonPilon** [derrynknife/SurPyval#21]
This is more relevant for testing regression models. Since real-life data never fits neatly into a "box", it is useful to compare results against other implementations (lifelines uses R's `survival` and `flexsurvreg` libraries). 

openjournals/joss-reviews#3484

**Comment by derrynknife** [comment]
I only completed the regression model fitters after writing the paper.  And in the paper I make no claims about regression models. If I remove all references to regression models, and submit a major change in future, can we exclude the regression features from this review?

**Comment by CamDavidsonPilon** [comment]
I'm fine with dropping #20, but then I would still suggest testing real-life data in non-regression tests and comparing vs R and/or lifelines. This can also test the robustness of your `_parameter_initialiser` methods (since we'll be testing it against different-distributed data points)

**Comment by derrynknife** [comment]
Removed reference to regression in docs. 457c77e4ca44e6ffe7b68138e53a61ff90b81276

**Comment by derrynknife** [comment]
Added tests to lifelines data sets. See e3da8d782ea5e8f79d5c120122de84af89339586
