### ISSUE TITLE
[JOSS Review] Parametric form in docs 

### ISSUE THREAD

**Issue by CamDavidsonPilon** [derrynknife/SurPyval#4]
One of the annoying things about statistics is all the different ways one can parameterize a distribution. For absolute clarity to users, I think it's important to have the parametric form used in the docs. It's been done for some [distributions](https://surpyval.readthedocs.io/en/latest/exponential.html), but needs to be there for all (example [missing](https://surpyval.readthedocs.io/en/latest/lognormal.html). 

https://github.com/openjournals/joss-reviews/issues/3484

**Comment by derrynknife** [comment]
Thanks @CamDavidsonPilon, I've updated all the docstrings for each distribution. The parameterisation should now be clear for all the distributions.

Couldn't agree more that different parameterisations can be annoying.

**Comment by CamDavidsonPilon** [comment]
Also needs docs / parametric forms on the regression models / life models.
