### ISSUE TITLE
[JOSS review] __str__ vs __repr__ in classes

### ISSUE THREAD

**Issue by CamDavidsonPilon** [derrynknife/SurPyval#5]
In an IPython console, the following produces different results:
```
> model
> print(model)
```

Take a look at `__repr__` instead of using [`__str__`] (https://github.com/derrynknife/SurPyval/blob/768595da11fa15410c3ad5b44bb1a7caf615b9e7/surpyval/parametric/offset_parametric.py#L23) to align these

**Comment by derrynknife** [comment]
Thanks @CamDavidsonPilon, I've change the offset parametric and parametric classes to use `__repr__` instead of `__str__`
